// <auto-generated />
using System;
using System.Collections.Generic;
using AI.DocumentIntelligence.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI.DocumentIntelligence.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723230304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.AiUsageMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation_type");

                    b.Property<TimeSpan>("ProcessingTime")
                        .HasColumnType("interval")
                        .HasColumnName("processing_time");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty<Dictionary<string, object>>("TokenUsage", "AI.DocumentIntelligence.Domain.Entities.AiUsageMetric.TokenUsage#TokenUsage", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("integer")
                                .HasColumnName("token_completion_tokens");

                            b1.Property<decimal>("EstimatedCost")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("token_estimated_cost");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("integer")
                                .HasColumnName("token_prompt_tokens");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_usage_metrics_user_id_created_at_utc");

                    b.ToTable("ai_usage_metrics", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.AnalysisSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("capability");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomQuestion")
                        .HasColumnType("text")
                        .HasColumnName("custom_question");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("text")
                        .HasColumnName("executive_summary");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<TimeSpan?>("ProcessingTime")
                        .HasColumnType("interval")
                        .HasColumnName("processing_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.PrimitiveCollection<List<string>>("_actionItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_items");

                    b.PrimitiveCollection<List<Guid>>("_documentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_ids");

                    b.PrimitiveCollection<List<string>>("_keyFindings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_findings");

                    b.PrimitiveCollection<List<string>>("_recommendations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations");

                    b.PrimitiveCollection<List<string>>("_risksIdentified")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risks_identified");

                    b.ComplexProperty<Dictionary<string, object>>("TokenUsage", "AI.DocumentIntelligence.Domain.Entities.AnalysisSession.TokenUsage#TokenUsage", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("integer")
                                .HasColumnName("token_completion_tokens");

                            b1.Property<decimal>("EstimatedCost")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("token_estimated_cost");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("integer")
                                .HasColumnName("token_prompt_tokens");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_analysis_sessions_owner_id");

                    b.ToTable("analysis_sessions", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_audit_logs_created_at_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.ComplexProperty<Dictionary<string, object>>("TokenUsage", "AI.DocumentIntelligence.Domain.Entities.ChatMessage.TokenUsage#TokenUsage", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("integer")
                                .HasColumnName("token_completion_tokens");

                            b1.Property<decimal>("EstimatedCost")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("token_estimated_cost");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("integer")
                                .HasColumnName("token_prompt_tokens");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId")
                        .HasDatabaseName("ix_chat_messages_chat_session_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.PrimitiveCollection<List<Guid>>("_documentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_ids");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_chat_sessions_owner_id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ComparisonSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComparisonType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("comparison_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExecutiveOverview")
                        .HasColumnType("text")
                        .HasColumnName("executive_overview");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<TimeSpan?>("ProcessingTime")
                        .HasColumnType("interval")
                        .HasColumnName("processing_time");

                    b.Property<string>("RiskAnalysis")
                        .HasColumnType("text")
                        .HasColumnName("risk_analysis");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.PrimitiveCollection<List<Guid>>("_documentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_ids");

                    b.PrimitiveCollection<List<string>>("_keyDifferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_differences");

                    b.PrimitiveCollection<List<string>>("_recommendations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations");

                    b.ComplexProperty<Dictionary<string, object>>("TokenUsage", "AI.DocumentIntelligence.Domain.Entities.ComparisonSession.TokenUsage#TokenUsage", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("integer")
                                .HasColumnName("token_completion_tokens");

                            b1.Property<decimal>("EstimatedCost")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("token_estimated_cost");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("integer")
                                .HasColumnName("token_prompt_tokens");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_comparison_sessions_owner_id");

                    b.ToTable("comparison_sessions", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_documents_owner_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at_utc");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.AnalysisSession", b =>
                {
                    b.OwnsMany("AI.DocumentIntelligence.Domain.ValueObjects.Citation", "ReferencedSources", b1 =>
                        {
                            b1.Property<Guid>("AnalysisSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<double>("ConfidenceScore")
                                .HasColumnType("double precision")
                                .HasColumnName("confidence_score");

                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid")
                                .HasColumnName("document_id");

                            b1.Property<string>("DocumentName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("document_name");

                            b1.Property<int>("PageNumber")
                                .HasColumnType("integer")
                                .HasColumnName("page_number");

                            b1.Property<string>("ParagraphReference")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("paragraph_reference");

                            b1.Property<string>("Snippet")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("snippet");

                            b1.HasKey("AnalysisSessionId", "__synthesizedOrdinal");

                            b1.ToTable("analysis_sessions");

                            b1.ToJson("referenced_sources");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisSessionId");
                        });

                    b.Navigation("ReferencedSources");
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("AI.DocumentIntelligence.Domain.Entities.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("AI.DocumentIntelligence.Domain.ValueObjects.Citation", "Citations", b1 =>
                        {
                            b1.Property<Guid>("ChatMessageId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<double>("ConfidenceScore")
                                .HasColumnType("double precision")
                                .HasColumnName("confidence_score");

                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid")
                                .HasColumnName("document_id");

                            b1.Property<string>("DocumentName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("document_name");

                            b1.Property<int>("PageNumber")
                                .HasColumnType("integer")
                                .HasColumnName("page_number");

                            b1.Property<string>("ParagraphReference")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("paragraph_reference");

                            b1.Property<string>("Snippet")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("snippet");

                            b1.HasKey("ChatMessageId", "__synthesizedOrdinal");

                            b1.ToTable("chat_messages");

                            b1.ToJson("citations");

                            b1.WithOwner()
                                .HasForeignKey("ChatMessageId");
                        });

                    b.Navigation("Citations");
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ComparisonSession", b =>
                {
                    b.OwnsMany("AI.DocumentIntelligence.Domain.ValueObjects.Citation", "SourceCitations", b1 =>
                        {
                            b1.Property<Guid>("ComparisonSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<double>("ConfidenceScore")
                                .HasColumnType("double precision")
                                .HasColumnName("confidence_score");

                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid")
                                .HasColumnName("document_id");

                            b1.Property<string>("DocumentName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("document_name");

                            b1.Property<int>("PageNumber")
                                .HasColumnType("integer")
                                .HasColumnName("page_number");

                            b1.Property<string>("ParagraphReference")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("paragraph_reference");

                            b1.Property<string>("Snippet")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("snippet");

                            b1.HasKey("ComparisonSessionId", "__synthesizedOrdinal");

                            b1.ToTable("comparison_sessions");

                            b1.ToJson("source_citations");

                            b1.WithOwner()
                                .HasForeignKey("ComparisonSessionId");
                        });

                    b.OwnsMany("AI.DocumentIntelligence.Domain.ValueObjects.ChangeLogEntry", "DetailedChangeLog", b1 =>
                        {
                            b1.Property<Guid>("ComparisonSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<string>("NewContent")
                                .HasColumnType("text")
                                .HasColumnName("new_content");

                            b1.Property<string>("OldContent")
                                .HasColumnType("text")
                                .HasColumnName("old_content");

                            b1.Property<string>("Section")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("section");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("status");

                            b1.HasKey("ComparisonSessionId", "__synthesizedOrdinal");

                            b1.ToTable("comparison_sessions");

                            b1.ToJson("detailed_change_log");

                            b1.WithOwner()
                                .HasForeignKey("ComparisonSessionId");
                        });

                    b.Navigation("DetailedChangeLog");

                    b.Navigation("SourceCitations");
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.Document", b =>
                {
                    b.OwnsOne("AI.DocumentIntelligence.Domain.ValueObjects.FileMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("metadata_content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("metadata_file_name");

                            b1.Property<int>("PageCount")
                                .HasColumnType("integer")
                                .HasColumnName("metadata_page_count");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("metadata_size_bytes");

                            b1.HasKey("DocumentId");

                            b1.ToTable("documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
