// <auto-generated />
using System;
using System.Collections.Generic;
using AI.DocumentIntelligence.Domain.ValueObjects;
using AI.DocumentIntelligence.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AI.DocumentIntelligence.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260630232027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.AiUsageMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_type");

                    b.Property<TimeSpan>("ProcessingTime")
                        .HasColumnType("interval")
                        .HasColumnName("processing_time");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_ai_usage_metrics_created_at_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_usage_metrics_user_id");

                    b.ToTable("ai_usage_metrics", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.AnalysisSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("capability");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomQuestion")
                        .HasColumnType("text")
                        .HasColumnName("custom_question");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("text")
                        .HasColumnName("executive_summary");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<TimeSpan?>("ProcessingTime")
                        .HasColumnType("interval")
                        .HasColumnName("processing_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<List<string>>("_actionItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_items");

                    b.Property<List<Guid>>("_documentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_ids");

                    b.Property<List<string>>("_keyFindings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_findings");

                    b.Property<List<string>>("_recommendations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations");

                    b.Property<List<Citation>>("_referencedSources")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("referenced_sources");

                    b.Property<List<string>>("_risksIdentified")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risks_identified");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_analysis_sessions_owner_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_analysis_sessions_status");

                    b.ToTable("analysis_sessions", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_audit_logs_created_at_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<List<Citation>>("_citations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("citations");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId")
                        .HasDatabaseName("ix_chat_messages_chat_session_id");

                    b.HasIndex("ChatSessionId", "Ordinal")
                        .HasDatabaseName("ix_chat_messages_session_ordinal");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<List<Guid>>("_documentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_ids");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_chat_sessions_owner_id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ComparisonSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComparisonType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("comparison_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExecutiveOverview")
                        .HasColumnType("text")
                        .HasColumnName("executive_overview");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<TimeSpan?>("ProcessingTime")
                        .HasColumnType("interval")
                        .HasColumnName("processing_time");

                    b.Property<string>("RiskAnalysis")
                        .HasColumnType("text")
                        .HasColumnName("risk_analysis");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<List<ChangeLogEntry>>("_detailedChangeLog")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detailed_change_log");

                    b.Property<List<Guid>>("_documentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_ids");

                    b.Property<List<string>>("_keyDifferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_differences");

                    b.Property<List<string>>("_recommendations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations");

                    b.Property<List<Citation>>("_sourceCitations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_citations");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_comparison_sessions_owner_id");

                    b.ToTable("comparison_sessions", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_documents_owner_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_documents_status");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<string>("ParagraphReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("paragraph_reference");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_chunks_document_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_document_chunks_embedding_hnsw_cosine");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at_utc");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_unique");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.AiUsageMetric", b =>
                {
                    b.OwnsOne("AI.DocumentIntelligence.Domain.ValueObjects.TokenUsage", "TokenUsage", b1 =>
                        {
                            b1.Property<Guid>("AiUsageMetricId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("integer")
                                .HasColumnName("completion_tokens");

                            b1.Property<decimal>("EstimatedCost")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("estimated_cost");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("integer")
                                .HasColumnName("prompt_tokens");

                            b1.HasKey("AiUsageMetricId");

                            b1.ToTable("ai_usage_metrics");

                            b1.WithOwner()
                                .HasForeignKey("AiUsageMetricId");
                        });

                    b.Navigation("TokenUsage")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.AnalysisSession", b =>
                {
                    b.OwnsOne("AI.DocumentIntelligence.Domain.ValueObjects.TokenUsage", "TokenUsage", b1 =>
                        {
                            b1.Property<Guid>("AnalysisSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("integer")
                                .HasColumnName("completion_tokens");

                            b1.Property<decimal>("EstimatedCost")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("estimated_cost");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("integer")
                                .HasColumnName("prompt_tokens");

                            b1.HasKey("AnalysisSessionId");

                            b1.ToTable("analysis_sessions");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisSessionId");
                        });

                    b.Navigation("TokenUsage")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("AI.DocumentIntelligence.Domain.Entities.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AI.DocumentIntelligence.Domain.ValueObjects.TokenUsage", "TokenUsage", b1 =>
                        {
                            b1.Property<Guid>("ChatMessageId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("integer")
                                .HasColumnName("completion_tokens");

                            b1.Property<decimal>("EstimatedCost")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("estimated_cost");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("integer")
                                .HasColumnName("prompt_tokens");

                            b1.HasKey("ChatMessageId");

                            b1.ToTable("chat_messages");

                            b1.WithOwner()
                                .HasForeignKey("ChatMessageId");
                        });

                    b.Navigation("TokenUsage")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ComparisonSession", b =>
                {
                    b.OwnsOne("AI.DocumentIntelligence.Domain.ValueObjects.TokenUsage", "TokenUsage", b1 =>
                        {
                            b1.Property<Guid>("ComparisonSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("integer")
                                .HasColumnName("completion_tokens");

                            b1.Property<decimal>("EstimatedCost")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("estimated_cost");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("integer")
                                .HasColumnName("prompt_tokens");

                            b1.HasKey("ComparisonSessionId");

                            b1.ToTable("comparison_sessions");

                            b1.WithOwner()
                                .HasForeignKey("ComparisonSessionId");
                        });

                    b.Navigation("TokenUsage")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.Document", b =>
                {
                    b.OwnsOne("AI.DocumentIntelligence.Domain.ValueObjects.FileMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("file_name");

                            b1.Property<int>("PageCount")
                                .HasColumnType("integer")
                                .HasColumnName("page_count");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("size_bytes");

                            b1.HasKey("DocumentId");

                            b1.ToTable("documents");

                            b1.ToJson("metadata");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("AI.DocumentIntelligence.Domain.Entities.Document", null)
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AI.DocumentIntelligence.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
